---
title: "A Very Short Introduction to Stata"
description: |
  The basic *philosophy* of Stata.
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    highlight: haddock
    toc: no
  pdf_document: 
    toc: no
    latex_engine: xelatex
  html_document:
    highlight: haddock
mainfont: Futura
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

The basic philosophy of Stata---“Stata in one sentence”---is: 

`do_something to_variable(s), options`

The general idea of most Stata commands is `command variable(s), options`. Often it is not necessary to use any options since the authors of Stata have done such a good job of thinking about the defaults. Commands that you actually type are represented in `monospace` font. `x` and `y` refer to variables in your data.

| Task | Command | 
|------|-----|
| Open data | `use mydata.dta` |
| Descriptive statistics | `summarize x y` |
| Frequencies | `tabulate x` |
| Correlation | `corr x y` |
| Regression | `regress y x` |
| Logistic Regression | `logit y x, or` [^logit] |
| Multilevel Model | `mixed y x || group:`|
| Structural Equation Modeling | `sem (y <- x m) (m <- x)` |
| Histogram | `histogram x` [^graph]|
| Bar Graph | `graph bar, over(x)` |
| Bar Graph (of means) | `graph bar y, over(x)` |
| Pie Chart | `graph pie, over(x)` |
| Scatterplot | `twoway scatter y x` |

[^logit]: Here we need to use the `,or` option to ask for *odds ratios* instead of *logit coefficients*.
[^graph]: For graphing commands, you can often add options after a `,`. e.g. `title("title of the graph")`, `xtitle("title of the x axis")`, `ytitle("title of the y axis")`.



